# Generated by Django 6.0.2 on 2026-02-21 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_group_members_group_type_groupmembermodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='chat.GroupMemberModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
