# Generated by Django 6.0.2 on 2026-08-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembermodel',
            name='creator',
            field=models.BooleanField(default=False),
        ),
    ]
