# Generated by Django 5.2.7 on 2026-08-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email',
            field=models.BooleanField(default=False),
        ),
    ]
