# Generated by Django 5.2.7 on 2026-08-27 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_is_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verigication_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
