# Generated by Django 5.2.7 on 2026-08-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_verigication_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verigication_uuid',
            new_name='verification_uuid',
        ),
    ]
