# Generated by Django 5.2.7 on 2026-09-04 21:47

import login.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_rename_verigication_uuid_user_verification_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[login.validators.validate_avater_size]),
        ),
    ]
