# Generated by Django 5.2.7 on 2026-09-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_email', True)), fields=('email',), name='unique_confirmed_email'),
        ),
    ]
