# Generated by Django 6.0.2 on 2026-08-11 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_groupmembermodel_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembermodel',
            old_name='creator',
            new_name='is_creator',
        ),
    ]
