# Generated by Django 5.2.7 on 2026-08-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_group_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='avatars/'),
        ),
    ]
