# Generated by Django 5.2.7 on 2026-09-05 18:25

import login.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_group_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='avatars/', validators=[login.validators.validate_avatar_size]),
        ),
    ]
