# Generated by Django 5.2.7 on 2026-10-04 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_groupmembermodel_unique_group_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
