# Generated by Django 5.2.7 on 2026-10-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_message_msg_group_ts_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='msg_group_ts_idx',
        ),
    ]
