# Generated by Django 5.2.7 on 2026-10-08 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_message_msg_group_ts_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmembermodel',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['group', '-timestamp'], name='event_group_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['group', '-timestamp'], name='msg_group_ts_idx'),
        ),
    ]
